name: Unit test runner
on:
  push:
  pull_request:

jobs:
  unit_test_runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with test
        run: mvn clean test

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          artifact: test-results
          name: Junit test
          reporter: java-junit
