name: Unit test runner
on:
  # run on every push except main
  push:
    branches-ignore:
      - main

jobs:
  buid_and_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with test
        run: mvn clean test

      - name: Generate test report
        run: mvn jacoco:report

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: ${{ github.workspace }}/target/site/jacoco

      - name: Print the test report
        uses: Madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          # Github personal token to add commits to Pull Request
          token: ${{ secrets.GITHUB_TOKEN }}

